### ISSUE TITLE
should we advertize service accounts ? 

### ISSUE THREAD

**Issue by 12rambau** [gee-community/ee-initialize-github-actions#3]
As github actions can be run on regular basis, would it make sense to advertise the 2 existing routes to create the json credential files: 
- ee.Authenticate (done) 
- a service account key 

I personnaly only use json keys as it's preventing from accident. If anything goes wrong I switch off the key from my google console and I stop paying for unwanted jobs.

**Comment by jdbcode** [comment]
Yes, definitely! and also workload identify federation (Xee is using it). I aggregated this issue into #5.
