### ISSUE TITLE
should we advertize pytest-gee as well ? 

### ISSUE THREAD

**Issue by 12rambau** [gee-community/ee-initialize-github-actions#4]
One of the biggest use of github actions is to create CI tests. I started to code the pytest-gee plugin to this objective (it's widely used in ipygee, geeservermap, eeauth and geetools). It requires 1 extra environment value to work out of the box from your explainations. 

Note that once I get the static plots back to geetools I will update this plugin package to make it easier to use (directly digesting image and featurecollection).

**Comment by jdbcode** [comment]
This is great, Pierrick! I didn't know about pytest-gee.
My modivation for this repo was helping a person using private credentials to get set up. While I was going through the effort to test, I figured I make it public. I've included this issue to mention and link to pytest-gee in #5.
